name: "Build"

on: [push, pull_request]

jobs:
  Matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Matrix
        id: matrix
        uses: Invicton-Labs/terraform-module-testing/matrix@v0.4.0
        with:
          minimum_tf_version: '1.10.3'
          additional_runners: 'macos-13, windows-2019'

      - name: Output Matrix
        run: |
          echo "Strategy: ${{ steps.matrix.outputs.strategy }}"

    outputs:
      strategy: ${{ steps.matrix.outputs.strategy }}
          
  Test:
    needs: [Matrix]
    strategy: ${{ fromJSON(needs.Matrix.outputs.strategy)}}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    steps:
      - name: Initialize
        id: init
        uses: Invicton-Labs/terraform-module-testing/initialize@v0.4.0
        with:
          tf_path: .
      - name: Test
        id: test
        run: terraform test
          
  # This job just waits for all other jobs to pass. We have it here
  # so our branch protection rule can reference a single job, instead
  # of needing to list every matrix value of every job above.
  Passed:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - name: Mark tests as passed
      run: echo "🎉"